apiVersion: v1
kind: PersistentVolume
metadata:
  name: streamvolume
spec:
  accessModes: 
    - ReadWriteOnce

  capacity:
    storage: 2Gi

  hostPath:
    path: "/home/ubuntu/video_streaming_dashboard_k8s/server"
